### PR TITLE
DB_PASSWORD and User creation command line

### PR DESCRIPTION
**Pull request by yalh76**
I'm working to package Anfora for [Yunohost](https://yunohost.org), to make it available easily for end users.

For security reasons, I added:
- postgresql database password

To automate installation from end to end, I added:
- command line to create a user: `pipenv run python commands.py -u --username test --password MyPaSsWoRd --email test@example.com --is_admin True`

For the command line, I have an error: `WARNING ERROR:root:[Errno 2] No such file or directory: '/home/yunohost.app/anfora/uploads/avatars/q9gGG6Q.jpeg'` that I can't manage

PS: There are missing files in the anfora repository:

- streaming/index.js
- huey_consumer.py
- tasks.main.huey

### CODE REVIEW

**Comment by yabirgb** [comment]
Hi @yalh76 ! Thanks for the PR. The error might be an issue with the directory tree. Have you created The fordel `/home/yunohost.app/anfora/uploads/avatars` and `/home/yunohost.app/anfora/uploads/max_resolution`? The first one is where user avatars are stored. When you create a new user it tries to store it's avatar there. 

About the files you mention:

* `index.js` is obsolete since I moved the streaming API from js to python. The porpouse was to use only python in the server.
* `huey_consumer.py` you don't need to add this file. It's from a python module ([huey](https://github.com/coleifer/huey)) and as you can read [here](https://github.com/coleifer/huey#running-the-consumer) this is the way to call the module. You only need to install it and call it under the environment.
* `tasks.main.huey` is calling just the huey module in the task folder at the main file, you shouldn't have issues with this

It's true that the other day I set up the server in my laptop and there was a couple of settings that I forgot to document and I'll do it tomorrow. Now I was going to sleep but saw your PR and I wanted to clarify this. Also I'll review it tomorrow too. 

Again, thank you for your collaboration <3

**Comment by yabirgb** [comment]
Oh, by a fast look I see that you found the missing imports. Thank you! I'll add it to the documentation ASAP tomorrow

**Comment by yalh76** [comment]
Thanks for the quick response. I will deep dive in them. 

Just to let you know the current package anfora for Yunohost : https://github.com/YunoHost-Apps/anfora_ynh/tree/testing and the install steps: https://github.com/YunoHost-Apps/anfora_ynh/blob/testing/scripts/install

The package is not ready but I'll let you know

**Comment by yalh76** [comment]
> 
> It's true that the other day I set up the server in my laptop and there was a couple of settings that I forgot to document and I'll do it tomorrow. Now I was going to sleep but saw your PR and I wanted to clarify this. Also I'll review it tomorrow too.

Just to let you know that I'm a linux beginner, never learn Python and first time I'm writing something in Python... So it's more copy/paste from your code and adaptation. Don't hesitate to make changes if needed.

**Comment by yalh76** [comment]
> 
> 
> Hi @yalh76 ! Thanks for the PR. The error might be an issue with the directory tree. Have you created The fordel `/home/yunohost.app/anfora/uploads/avatars` and `/home/yunohost.app/anfora/uploads/max_resolution`? The first one is where user avatars are stored. When you create a new user it tries to store it's avatar there.

Thanks, no more error during user creation using `pipenv run python commands.py -u --username test --password MyPaSsWoRd --email test@example.com --is_admin True` and user created in the database

**Comment by yalh76** [comment]
> 
> 
> Oh, by a fast look I see that you found the missing imports. Thank you! I'll add it to the documentation ASAP tomorrow

Thanks, I will wait for the documentation update to move forward ont the anfora package for yunohost :)

**Comment by yabirgb** [comment]
@yalh76 I've added a section to the installation process including the variables used for configuration https://anfora.app/documentation/settings/ The ones that you are missing are:

-  `REG_OPEN` boolean default to True (`REG_OPEN=True`)
- `SMTP_PORT` should be a integer  (`SMTP_PORT=465`)
- `DEBUG` boolean default to False (`DEBUG=False`)

Also I want to mention that I don't know how yunohost works but the user should be able to create it's own secret and salt_code. Currently I change this values manually but I don't know if it possible when you build a server using yunohost

**Comment by yalh76** [comment]
> 
> 
> @yalh76 I've added a section to the installation process including the variables used for configuration https://anfora.app/documentation/settings/ The ones that you are missing are:
> 
>     * `REG_OPEN` boolean default to True (`REG_OPEN=True`)
> 
>     * `SMTP_PORT` should be a integer  (`SMTP_PORT=465`)
> 
>     * `DEBUG` boolean default to False (`DEBUG=False`)
Thanks, I will add them to the yunohost package

**Comment by yalh76** [comment]
> Also I want to mention that I don't know how yunohost works but the user should be able to create it's own secret and salt_code. Currently I change this values manually but I don't know if it possible when you build a server using yunohost

Yunohost is a Debian with a webadmin panel to let people do self-hosting on RaspberryPi, server or virtual machine.

They can install several apps, like Mastodon, Pleroma, Nextcloud, etc.. with one click.

For secret and salt code, they are randomly generated during install.

https://github.com/YunoHost-Apps/anfora_ynh/blob/e483f44480d06f52b3bcc6cfa374e42d07706a82/scripts/install#L34

**Comment by yabirgb** [comment]
Nice, I've learnt how to merge just some commits so I can merge your changes. If you need something else just tell me

**Comment by yalh76** [comment]
> 
> 
> Nice, I've learnt how to merge just some commits so I can merge your changes. If you need something else just tell me @yalh76

Great :)

The [Readme](https://github.com/anforaProject/anfora/blob/master/README.md) and the [documentation ](https://anfora.app/documentation/getting-started/) still speak of `anfora node server` but you said that index.js and that you moved the streaming API from js to Python.
What is the command line to start the streaming service ?

To start the main anfora service is it:
`pipenv run python main.py` as written in the [documentation ](https://anfora.app/documentation/getting-started/)
or
`pipenv run gunicorn --bind 0.0.0.0:3000 main:app --keep-alive 5 --log-level DEBUG --workers 8 --threads=4` as written in the [readme](https://github.com/anforaProject/anfora/blob/master/README.md)

**Comment by yabirgb** [comment]
> The [Readme](https://github.com/anforaProject/anfora/blob/master/README.md) and the [documentation ](https://anfora.app/documentation/getting-started/) still speak of `anfora node server` but you said that index.js and that you moved the streaming API from js to Python.
> What is the command line to start the streaming service ?
> 
> To start the main anfora service is it:
> `pipenv run python main.py` as written in the [documentation ](https://anfora.app/documentation/getting-started/)
> or
> `pipenv run gunicorn --bind 0.0.0.0:3000 main:app --keep-alive 5 --log-level DEBUG --workers 8 --threads=4` as written in the [readme](https://github.com/anforaProject/anfora/blob/master/README.md)

Sorry, when I created the documentation I forgot to update the readme. What you need to do is start the server like the documentation says

`pipenv run python main.py
`

**Comment by yalh76** [comment]
> `pipenv run python main.py`
> 
> The node server doesn't exists anymore and when you execute the previous line you start the server and the streaming api

Ok, then does this means that nginx configuration has to be changed because it's indicated in the documentation that `/api/v1/streaming/` is proxyed to `http://127.0.0.1:4000;` and there is nothing listening on port 4000

**Comment by yabirgb** [comment]
Yes, you are right

**Pull request merged**
